version: '3.9'

services:
  env_ruby:
    container_name: env_ruby
    image: ruby:latest
    hostname: env_ruby
    volumes:
      - ./workspace:/workspace
    working_dir: /workspace
    command: ["/bin/bash", "-c", "trap : TERM INT; sleep infinity & wait"]
